
vars:
  - params.py:RANDOM_SEED,LocationConfig,CreateDataConfig,TrainingConfig,WandbConfig

stages:
  create_dataset:
    cmd: python create_dataset.py
    params:
      - params.py:
        - CreateDataConfig
        - RANDOM_SEED
    deps:
      - ${LocationConfig.raw_data}
    outs:
      - ${LocationConfig.new_data}

  training:
    cmd: python train.py
    params:
      - icp_clustering/params.py:
          - WandbConfig
          - TrainingConfig
          - RANDOM_SEED
          - CreateDataConfig
          - LocationConfig
    deps:
      - ${LocationConfig.new_data}
    outs:
      - "${LocationConfig.best_model}"
      - "${LocationConfig.checkpoints_dir}"